encoder_params:
  in_channels: 3
  hidden_dims: null
  latent_dim: 64

decoder_params:
  hidden_dims: null
  latent_dim: 64

loss_params:
  kl_coeff: null # Placeholder not actually used

vq_params:
  num_embeddings: 512
  embedding_dim: 64
  beta: 0.25

exp_params:
  model_name: 'vq_vae'
  dataset: celeba
  data_path: "kaggle"
  img_size: 64
  crop_size: 128
  batch_size: 256 # Better to have a square number
  LR: 0.001
  template: "vq vae"

trainer_params:
  gpus: 1
  max_epochs: 30